[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs]
    spec    = "cypress/e2e/**/*.cy.ts"
    browser = "chrome"
    record  = false
